name: flutter_mjpeg
description: Flutter widget to show mjpeg stream from URL
version: 1.2.0
author: jaumard <jimmy.aumard@gmail.com>
homepage: https://github.com/mylisabox/flutter_mjpeg

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.7.8 <2.0.0"

dependencies:
  flutter_hooks: ^0.6.0
  http: ^0.12.0+2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
